### ISSUE TITLE
Clearing boxes functionality does not terminate existing WebWorkers

### ISSUE THREAD

**Issue by magoni** [DDMAL/west.js#1]
Currently, clearAllBoxes() only clears the HTML in a box without terminating the existing WebWorker process for that box. From my understanding, upon creating a webworker, we'll have to save the reference to the boxWorker instance we created in order to send it a message to terminate itself (i.e. to run a method containing `self.close()`.) Not sure how to do this when we're creating WebWorkers using the events system.

**Comment by ahwitz** [comment]
What I think might be easiest:
-Store them in an array
-Whenever a new action is called, iterate through the array and stop execution of every worker where boxWorker.boxNumber (line 15 in west.js) == the number of the box called
-If sending a second message to the worker is possible, send it a message with a specific parameter that tells it to stop execution
-Else, throw an if around line 24 (if boxWorker.hasStoppedExecution or something)

**Comment by magoni** [comment]
Closed via https://github.com/DDMAL/west.js/commit/60336c4312dc1f83fe9b76cf786bb1f795486a57 and https://github.com/DDMAL/west.js/commit/9d3f21920ca4a5f481f0c5fcf9ecb9c9bffef428.
